# Generated by Django 3.0.7 on 2020-07-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voisin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('about_me', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_voisin', models.IntegerField()),
                ('favoris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Voisin')),
            ],
        ),
    ]
